### ISSUE TITLE
arrow.ParserError does not exist in file canvas_object.py

### ISSUE THREAD

**Issue by w-mcilhagga** [ucfopen/canvasapi#645] opened 2024-02-08 13:55 UTC
# Bug

when calling course = canvas.get_course(id) the following occurs:
```
File "path-to\canvasapi\canvas_object.py", line 69, in set_attributes
    except arrow.ParserError:

  AttributeError: module 'arrow' has no attribute 'ParserError
```

# Fix

On line 69 of file 'canvas_object.py' it says
```
except arrow.ParserError:
```
Changing it to
```
except arrow.parser.ParserError:
```
fixes the bug

# Query?
Bug may arise because of different arrow versions?

**Comment by bennettscience** [comment] 2024-05-01 01:06
Cannot reproduce on 3.2.0.

**Comment by w-mcilhagga** [comment] 2024-05-01 06:13
It was an arrow version problem, I just assumed that pip would have
installed the correct version of arrow?

**Comment by bennettscience** [comment] 2024-05-01 10:55
I can't say for sure exactly what happened, but if `pip` fails to install a dependency for some reason, it will fall back to an older version. I'm guessing that's what happened in this case.

I'm assuming you've figured out a solution, but if not, you can try reinstalling with `python3 -m pip install canvasapi` to make sure you're running the most recent pip for your Python interpreter.

**Comment by w-mcilhagga** [comment] 2024-05-01 13:04
yep, all sorted

**Comment by bennettscience** [comment] 2024-05-01 13:31
Closing, possibly related to pip failing to find a compatible version of arrow.

**Closed by bennettscience** 2024-05-01 13:31 UTC
Labels: question

**Comment by bennettscience** [comment] 2024-05-01 14:50
[It looks like it was moved in 0.12.1](https://github.com/arrow-py/arrow/issues/535)? I thought about starting a new issue to switch over to using the `pyproject.toml` format to have more control (or flexibility?) over dependency management.
