### ISSUE TITLE
when turned off, DiscussionTopic.require_initial_post should be False instead of None

### ISSUE THREAD

**Issue by liblit** [ucfopen/canvasapi#78] opened 2017-09-18 00:08 UTC
When using `canvasapi` 0.6.0, calling `Course.get_discussion_topic` returns an instance of `DiscussionTopic`. The `require_initial_post` attribute of this instance is either `True` or `None`. In the latter case, a value of `False` would be preferable so that the attribute’s value is consistently a Python `bool`.

**Comment by Thetwam** [comment] 2017-09-18 20:07
I did a manual call to the discussion topics endpoint in Postman. It appears that despite their documentation, Canvas returns `null` for that parameter instead of `false`, hence why we return `None`. This appears to be the case in several other parameters as well, such as `podcast_has_student_posts` and `only_graders_can_rate`.

I am hesitant to add special cases to the library for these parameters. Instead, we should probably file a bug report with Canvas.

**Comment by jessemcbride** [comment] 2018-02-08 20:32
I've reported this to Canvas (https://github.com/instructure/canvas-lms/issues/1231). It does look like they've since corrected other erroneous null values (re: Matt's response), so once they fix this we should be able to close this issue.

**Comment by jessemcbride** [comment] 2018-03-15 14:44
Apparently this is intended behavior: https://github.com/instructure/canvas-lms/issues/1231#issuecomment-371184740

**Closed by jessemcbride** 2018-03-15 14:44 UTC
Labels: blocked, canvas-bug

**Comment by liblit** [comment] 2018-03-15 16:42
If Canvas insists that their code is correct, then their documentation is wrong. The two disagree, so they cannot both be right. But I suppose that’s Canvas’s problem, not yours. [I have pointed this out to them](https://github.com/instructure/canvas-lms/issues/1231#issuecomment-373442193), which is probably all we can do short of opening a new bug report against their documentation.
